name: Build Docker

# on: [push]
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      env:
        IMAGE: "kalemena/anaconda"
        VERSION: "3-2021.05"
      run: |
        sh .github/workflows/action-build-docker.sh
        # PUSH
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push ${IMAGE}:${VERSION}
        docker push ${IMAGE}:latest
        docker logout